version: '2'

services:
  imgsvc:
    image: imgsvc:0.2
    ports:
      - "8080:8080"
    volumes:
      - ./imgsvc:/root/imgsvc
    command: python /root/imgsvc/imgsvc.py
    depends_on:
      - solversvc
 solversvc:
    image: solversvc:0.1
    ports:
      - "8081:8080"
    volumes:
      - ./solversvc/apps:/root/apps
    command: java -jar /root/apps/star.jar
 client:
    image: solversvc:0.1
    ports:
      - "8081:8080"
    volumes:
      - ./solversvc/apps:/root/apps
    command: java -jar /root/apps/star.jar

